# Generated by Django 5.2.4 on 2025-07-12 08:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_subscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
